### ISSUE TITLE
Atelier Lydie & Suelle DX (Switch)

### ISSUE THREAD

**Issue by putmeinatoaster** [eArmada8/gust_stuff#1] opened 2023-04-10 12:04 UTC
Problem converting PC50A_MODEL_default.g1m
The zip contains the raw .elixer.gz, a folder that gust_tools generated, a folder containing the unfinished conversion with g1m_exporter.py, and a log.txt at time of error.

[PC50A_MODEL.zip](https://github.com/eArmada8/gust_stuff/files/11190273/PC50A_MODEL.zip)

**Comment by eArmada8** [comment] 2023-04-10 20:51
I'll take a look when I get a chance but it may be a few weeks!

**Comment by fioredio** [comment] 2023-04-13 22:51
The same issue is observed for steam version of Atelier Lydie & Suelle DX.
In case of PC50A, only PC50A_MODEL_P_Cloth_Arm.g1m and PC50A_MODEL_P_weight_Arm.g1m can be extracted with g1m_exporter_v1.3.4 (or v1.3.3a or v1.3.2a) whereas PC50A_MODEL_default.g1m cannot be extracted.
I attached herewith pc50a_model.elixir.gz of steam version.
[pc50a_model.elixir.gz](https://github.com/eArmada8/gust_stuff/files/11227098/pc50a_model.elixir.gz)

**Comment by eArmada8** [comment] 2023-04-15 07:12
Try turning off cloth transformation as a temporary measure. You can either change the variable at the top of the exporter script, or use the command line option.

**Comment by putmeinatoaster** [comment] 2023-04-15 07:33
Yes that does work. I had already made the edits I wanted to when I posted the issue. I figured you would like to know about some edge case. Or maybe not, I have only found 3 character models that have problems transforming the 4D stuff. All from this game and 2 of those models aren't even used in game as far as I know.
Thank you for sharing these tools btw, I had a lot of fun messing with them.

**Comment by eArmada8** [comment] 2023-04-15 14:58
Great to hear. I'll look at your files when I get a chance.

**Comment by fioredio** [comment] 2023-04-15 20:35
Thank you for kind explanation.
I confirmed that pc50a can be properly extracted with turning off cloth transformation.

**Comment by eArmada8** [comment] 2023-04-21 05:15
Ok, this should fix extracting pc50a with physics.  https://github.com/eArmada8/gust_stuff/commit/a4112855d8762d7778d396cc384d36b522635664

I'll push this into the next release eventually, but you can download the fixed exporter script now directly from source.  It's kind of an edge case / obscure fix and I really can't test further since I don't have this game, so I'm going to close the issue for now.

**Closed by eArmada8** 2023-04-21 05:15 UTC
